schema_version = "1.0.0"

id = "blammo"
version = "0.1.0"
name = "Blammo!"
tagline = "A Blender add-on"
maintainer = "okalex"
type = "add-on"

tags = ["3D View"]
blender_version_min = "4.2.0"

license = ["SPDX:GPL-2.0-or-later"]
